Introducing Numpy Library

1.Create Arrays

2.MultiDemensional Arrays

3.Randomly Generated Arrays

4.Element Wise operations


*   Comparison operations
*  Logical operations



5.Summarising operations

In [2]:
#we begin off by importing numpy
import numpy as np


**CREATE ARRAYS HERE**

In [3]:
#This function creates an array with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
#This function creates an array with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
#This function creates an array filled with 3s.
#The first digit determines how many 3s and in our case there are 5 of the 3s
np.full(5,3)

array([3, 3, 3, 3, 3])

In [9]:
#Below we create an array from a list
 [1,3,5,7,12]
a = np.array([1,3,5,7,12])
a

array([ 1,  3,  5,  7, 12])

In [12]:
#We change the value of the index at 2
a[2]=10
a

array([ 1,  3, 10,  7, 12])

In [13]:
#Create an array of 10 eelements with numbers from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#This creates an array of elements from 3 to 10
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
#Create an array with values from 0 to 100 with 11 elememnts
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

 **MULTIDIMENSIONAL ARRAYS**

In [19]:
#Create an array with 5 rows and 2 columns using the zeros function
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:

#Create an array from a list of lists
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


5

In [26]:
#This changes the elements from the second row on the second column
n[1,1] = 9

In [27]:
n

array([[1, 2, 3],
       [4, 9, 6],
       [7, 8, 9]])

In [29]:
#We change an entire row in an array
n[2]=[2,2,2]

In [30]:
n

array([[1, 2, 3],
       [4, 9, 6],
       [2, 2, 2]])

In [31]:
#we pick the second column only
n[:,2]

array([3, 6, 2])

In [33]:
# we can then alter this column
n[:,2] = [0,1,2]
n

array([[1, 2, 0],
       [4, 9, 1],
       [2, 2, 2]])

**RANDOMLY GENERATED ARRAYS**

In [40]:
'''The numbers generated by random.rand are pseudo random so to have the same numbers every time
we run this function we can employ random.seed'''

np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [41]:
#Here we use the function randn for the standard normal distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [42]:
#Here we use the function randint to generate random integers
np.random.seed(2)
np.random.randint(low =0, high=100, size=(6,4))

array([[40, 15, 72, 22],
       [43, 82, 75,  7],
       [34, 49, 95, 75],
       [85, 47, 63, 31],
       [90, 20, 37, 39],
       [67,  4, 42, 51]])

**ELEMENT WISE OPERATIONS**

In [46]:
#First lets create an array of 5 numbers 0 to 5 excluded using the function arange
a = np.arange(5)
a


array([0, 1, 2, 3, 4])

In [47]:
#To add a number to this array we can say

a + 1

array([1, 2, 3, 4, 5])

In [49]:
#To multiply a number by this array we can say

a * 4

array([ 0,  4,  8, 12, 16])

In [51]:
#we can also chain these
10 +(a*2)

array([10, 12, 14, 16, 18])

In [53]:
#lets save the chain tyo a different array
b = (10 + (a * 2 ))**2
b

array([100, 144, 196, 256, 324])

In [54]:
#Combining arrays
a + b

array([100, 145, 198, 259, 328])

**COMPARISON OPERATIONS**

In [56]:
a

array([0, 1, 2, 3, 4])

In [55]:
#To see the arrays of array a that are higher or equal to 2
a >= 2

array([False, False,  True,  True,  True])

In [57]:
b

array([100, 144, 196, 256, 324])

In [58]:
#which elements of array a are greater than array b

a > b

array([False, False, False, False, False])

In [60]:
#elements for which b > a
b > a

array([ True,  True,  True,  True,  True])

In [59]:
#we return an array for which b > a
b[b > a ]

array([100, 144, 196, 256, 324])

**SUMMARISING OPERATIONS**

In [62]:
a

array([0, 1, 2, 3, 4])

In [61]:
#return the smallest value in array a

a.min()

0

In [69]:
#return the highest value in array a

a.max()

4

In [63]:
a.sum()

10

In [64]:
a.mean()

2.0

In [65]:
a.std()

1.4142135623730951

In [67]:
#also works for the 2 dimensional arrays
n

array([[1, 2, 0],
       [4, 9, 1],
       [2, 2, 2]])