

**INTRODUCTION**



Here we are going to see how we apply linear algebra in Numpy

Important to Note is that in we can do the following multiplication operations:

1.   Vector- vector Multiplication
2.   Matrix - vector Multiplication
3.   Matrix - vector Multiplication


In linear Algebra, we have column vectors and to get a row vector we use a transpose which gives us a transpose of the column vector to get a row vector

A vector- vector multiplication gives us a single number











In [1]:
#we begin off by importing numpy as np
import numpy as np

In [11]:
#we then create two numpy arrays which are row vectors on which we shall carryout our linear algebra operations
#the shape property is used to get the shape of an array
u = np.array([1,0,0,2])
v = np.array([2,4,5,6])
u.shape
v.shape



In [15]:
#u.shape gives us a tuple and to get the first element of this tuple we shall use u.shape[0]
u.shape
#u.shape[0]

(4,)

In [16]:
#v.shape gives us a tuple and to get the first element of this tuple we shall use v.shape[0]
#v.shape
v.shape[0]

4

**MULTIPLICATION**

In [19]:
def vector_vector_multiplication(u,v):
  assert u.shape[0] == v.shape[0]

  n = u.shape[0] #the  number of elements in each array since they are equal
  result = 0.0 # this contains our dot product
  #Remember numpy arrays are indexed from 0 to n-1
  for i in range (n):
    result = result + u[i] * v[i]

  return result

In [20]:
vector_vector_multiplication(u,v)

14.0

In [21]:
#So above we were implementing a linear algebra multiplication but numpy has a function that can do this
u.dot(v)

14

**MATRIX- VECTOR MULTIPLICATION**

In Linear Algebra, each row of the matrix is multiplied by the column vector and in the end we should have a column vector
Remember the shape of the row and the column vector should match

So it is Row of Matrix * vector
So lets implement this numpy

In [24]:
a = np.array([[2,4,5,6],
             [1,2,1,2],
             [3,1,2,1]])
a

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [25]:
a.shape

(3, 4)

In [27]:
def matrix_vector_multiplication(a,v):
  #the number of columns in the matrix should match number of elements in vector
  assert a.shape[1] == v.shape[0]

  num_rows = a.shape[0]
  result = np.zeros(num_rows)# we initialize the dimension of resulting vector

  for i in range(num_rows):
    result[i] = vector_vector_multiplication(a[i],v)

  return result

In [32]:
matrix_vector_multiplication(a,v)

array([81., 27., 26.])

In [33]:
a.dot(v)

array([81, 27, 26])

**MATRIX - MATRIX MULTIPLICATION**

the result of a matrix matrix multiplication is a matrix.




In [34]:
b = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])
b

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [35]:
def matrix_matrix_multiplication(a,b):
  assert a.shape[1] == b.shape[0]

  num_rows = a.shape[0]
  num_cols = b.shape[1]

  result = np.zeros((num_rows,num_cols))

  for i in range(num_cols):
    bi = b[:, i]# this points to a particular column in our second matrix b
    abi = matrix_vector_multiplication(a, bi) #we multiply matrix a by the particular column and store the result in abi
    result[:, i] = abi # then we assign the abi to a column in the result matrix that we had earlier filled with zeros


  return result


In [36]:
matrix_matrix_multiplication(a,b)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [37]:
#we can confirm this with the dot method in numpy
a.dot(b)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

**IDENTITY MATRIX**
Is a square matrix with 1s on the diagonals and zeros every where else

If we multiply an a mtrix by an Identity matrix we get that particular matrix back

In [39]:
#To create an Identity matrix in Numpy
s =np.eye(4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
a

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [41]:
a.dot(s)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

**MATRIX INVERSE**
The inverse of a matrix is such that when we multiply it by the matrix we get an Identity matrix

Note: Only square matrices have inverse


In [73]:
# we turn into a square matrix by removing the last column
a_square = a[:,[0,1,2]]
a_square

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [77]:
a_square_inv = np.linalg.inv(a_square)
a_square_inv

array([[2., 4., 5.],
       [1., 2., 1.],
       [3., 1., 2.]])

In [80]:
a_square_inv.dot(a_square)

array([[ 1.00000000e+00, -5.55111512e-16, -4.44089210e-17],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])